spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/iot?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8
    username: root
    password: root
  profiles:
    active: server

server:
  tomcat:
    uri-encoding: UTF-8
    max-threads: 1000
    min-spare-threads: 30
  port: 8777
  servlet:
    context-path: /
